### ISSUE TITLE
Create Mockups

### ISSUE THREAD

**Issue by divaldez7464** [divaldez7464/frontend#1]

**Comment by JonBarroso** [comment]
Created a mockup to show what the future API is

Create pages for profile, login, logout, items added from the wishlist, random wishlist items

Backend to send information and retrieve information

User will be able to edit their accounts username and password

User will be able to edit the item they are buying

User can search for a specific item

User can click on already existing items

User can delete their accounts if they wanted to, there will also be a warning if delete account was pushed for confirmation

Admin will be able to delete accounts

Admin will have a specific login

**Comment by EnRangel** [comment]
As a user, I want to be able to login in to look at my profile page to be able to change my username and password.

As a user, I want to be able to go to the wishlist page to see all the items that I added in the past.

As a user, I want to be able to be able to add items to my wishlist.

As a user, I want to be able to make different list for different items.

As a user, I want to be able to change my profile icon.
